### ISSUE TITLE
expand submenu

### ISSUE THREAD

**Issue by nailfor** [RGRU/vue-simple-menu#1]
Добрый день.
При создании подменю компонента автоматически генерирует два свойства 
```
        // If item need expand behavoir
        // add property
        if (menuItem.list && !menuItem.uri) {
          menuItem.expand = true
          menuItem.expanded = true
        }
```
Подскажите, как сделать так, чтобы при открытии страницы элементы подменю были закрыты по умолчанию? Пробовал 
```
    id: 'item3',
    name: 'Name',
    expand: true,
    expanded: false,
    uri: '#',
    list: [
      {
        id: 'item3_1',
        name: 'Subname',
        uri: '/ship'
      },
    ]
```
но тогда он не реагирует на нажатие. Спасибо.

**Comment by nanomen** [comment]
@nailfor Добрый день!

Спасибо за сообщение. Добавили такую возможность.
В данных по элементу добавьте свойство expanded: false.

Например:
```js
...
rubrics: {
    id: 'rubrics',
    name: 'Рубрики',
    expanded: false,
    list: {}
}
...
```
Должно заработать!

**Comment by nailfor** [comment]
Так работает, спасибо. Однако из npm update почему то не обновляется, я клонировал репозитарий и пересобрал проект, тогда код обновился.

И еще нельзя ли rawMenuData принимать массивом?  Особого смысла именовать пункты меню нет, ошибка возникает только при проверки параметров - ожидается объект, остальное все работает точно так же.

**Comment by nanomen** [comment]
> Однако из npm update почему то не обновляется

Странно, проверил у меня обновилось. Может у вас в package.json стоит ограничение на обновление версии?

> И еще нельзя ли rawMenuData принимать массивом? 

Подумаем над реализацией!

**Comment by nailfor** [comment]
действительно, простите, так и есть.
