### ISSUE TITLE
Зачем минифицирован vue-simple-menu.js

### ISSUE THREAD

**Issue by vovs03** [RGRU/vue-simple-menu#2]
# Оба файла минифицированы.
**v.0.0.13**
`vue-simple-menu.js === vue-simple-menu.min.js`

- `/vue-simple-menu/dist/global/vue-simple-menu.js`
- `/vue-simple-menu/dist/global/vue-simple-menu.min.js`

**Comment by nanomen** [comment]
Добрый день, была ошибка сборки, спасибо, поправили.

**Comment by vovs03** [comment]
Отлично, спасибо.
