### ISSUE TITLE
Webpack 4.29.0 Concepts

### ISSUE THREAD

**Issue by vovs03** [RGRU/vue-simple-menu#3]
# Изменения в вэбпаке

В проекте сейчас используется зависимость: `"webpack": "^3.9.1"`, но в 4й версии будут отловлены предупреждения:
> WARNING in configuration
> The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
> You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

Произошло разделение конфига на два: `'development'` & `'production'`. Ссылка на концепт выше.

**Comment by nanomen** [comment]
Добрый день! На проекте использовалась старая сборка, обновили до webpack 4.

**Comment by vovs03** [comment]
Да, на Linux Mint 19 всё работет. Супер.

![screenshot from 2019-01-29 19-13-41](https://user-images.githubusercontent.com/21124057/51922438-16a1a800-23fa-11e9-86a7-bc31e1a6b6c2.png)
